---
- hosts: baseinstall
  become: true
  vars:
    src: "../src"
    local: "../local"    
    ansible_user: redarmorboy
    ansible_port: 42422
    ansible_ssh_private_key_file: conf/id_rsa
  tasks:
    - include: packages.yml
    - include: config.yml    
    - include: reboot.yml