---
- name: write sshd config
  copy:
    src: "{{ src }}/etc/ssh/sshd_config"
    dest: /etc/ssh/sshd_config
- name: restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted
- name: allow ssh in UFW
  community.general.ufw:
    rule: allow
    port: '42422'
- name: allow myth in UFW
  community.general.ufw:
    rule: allow
    port: '42424'
- name: enable UFW
  community.general.ufw:
    state: enabled
